# Generated by Django 5.0 on 2023-12-11 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('recover_password', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('where', models.CharField(max_length=100)),
                ('status_money', models.CharField(choices=[('kirim', 'kirim'), ('chiqim', 'chiqim')], max_length=20)),
                ('method_plase', models.CharField(choices=[('Oziq-ovqat', 'Oziq-ovqat'), ('Transport', 'Transport'), ('Kiyim-kechak', 'Kiyim-kechak'), ('Komunal', 'Komunal'), ('Axborot-vositalari', 'Axborot-vositalari'), ('Kafe-restoran', 'Kafe-restoran'), ('Taksi', 'Taksi'), ('Xizmatlar', 'Xizmatlar')], max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.user')),
            ],
        ),
    ]
