# Generated by Django 4.2.2 on 2023-11-27 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('where', models.CharField(max_length=100)),
                ('status_money', models.CharField(choices=[('kirim', 'kirim'), ('chiqim', 'chiqim')], max_length=20)),
                ('method_plase', models.CharField(choices=[('Oziq-ovqat', 'Oziq-ovqat'), ('Transport', 'Transport'), ('Kiyim-kechak', 'Kiyim-kechak'), ('Komunal', 'Komunal'), ('Axborot-vositalari', 'Axborot-vositalari'), ('Kafe-restoran', 'Kafe-restoran'), ('Taksi', 'Taksi'), ('Xizmatlar', 'Xizmatlar')], max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.user')),
            ],
        ),
    ]
